### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID for https://hydrogen-music.org/

### ISSUE THREAD

**Issue by trebmuh** [hydrogen-music/hydrogen-music#16] opened 2020-11-27 10:52 UTC
_(See https://github.com/hydrogen-music/hydrogen/issues/994)_

**Comment by theGreatWhiteShark** [comment] 2022-09-30 17:23
Duplicate of #9. I'll close here and suggest we transfer the discussion to that issue in order to keep it concise.

**Closed as completed by theGreatWhiteShark** 2022-09-30 17:23 UTC
